# Generated by Django 4.0.2 on 2022-10-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField()),
                ('home', models.CharField(max_length=30)),
                ('away', models.CharField(max_length=30)),
                ('home_goal', models.IntegerField()),
                ('away_goal', models.IntegerField()),
                ('home_goal_scorer', models.TextField()),
                ('away_goal_scorer', models.TextField()),
                ('date', models.DateTimeField()),
                ('home_lineup', models.TextField()),
                ('mom', models.CharField(max_length=30)),
            ],
        ),
    ]
