# Generated by Django 4.0.2 on 2022-10-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='away_lineup',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goal_scorer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal_scorer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_lineup',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='mom',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
