# Generated by Django 4.0.2 on 2022-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_match_options_match_away_lineup_match_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
