# Generated by Django 4.0.2 on 2022-10-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_match_live_match_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('club', models.CharField(max_length=50)),
                ('mp', models.IntegerField()),
                ('w', models.IntegerField()),
                ('d', models.IntegerField()),
                ('l', models.IntegerField()),
                ('pts', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goal_scorer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_lineup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal_scorer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_lineup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='live',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='mom',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='played',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
