# Generated by Django 4.0.2 on 2022-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_d1standing_d2standing_delete_standing'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
