# Generated by Django 4.0.2 on 2022-10-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_match_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('Division 1 League Cup', 'Division 1 League Cup'), ('Division 2 League Cup', 'Division 2 League Cup'), ('Champions League', 'Champions League'), ('Europa League', 'Europa League'), ('Super Cup', 'Super Cup'), ('International Match', 'International Match')], max_length=100, null=True),
        ),
    ]
