# Generated by Django 4.0.2 on 2022-10-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_match_match_status_match_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='foot_note',
            field=models.TextField(null=True),
        ),
    ]
