# Generated by Django 4.0.2 on 2022-10-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_match_foot_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='d1standing',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
