# Generated by Django 4.0.2 on 2022-10-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_d2standing_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('transferred_from', models.CharField(max_length=50)),
                ('transferred_to', models.CharField(max_length=50)),
                ('transferred_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='currentseason',
            options={'verbose_name_plural': 'Current season'},
        ),
    ]
