# Generated by Django 4.0.2 on 2022-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_news_transfer_alter_currentseason_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transferred_price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
