# Generated by Django 4.0.2 on 2022-10-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_transfer_transferred_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='foot_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
