# Generated by Django 4.0.2 on 2022-10-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_d1prevstanding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='D1PrevStanding',
        ),
    ]
