# Generated by Django 4.0.2 on 2022-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_d1prevstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('players', models.TextField()),
                ('highest_goal_scorer', models.CharField(max_length=50)),
                ('current_goals_scored', models.IntegerField()),
                ('all_goals_scored', models.IntegerField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('club', models.TextField()),
                ('highest_goal_scorer', models.CharField(max_length=50)),
                ('current_goals_scored', models.IntegerField()),
                ('all_goals_scored', models.IntegerField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
