# Generated by Django 4.0.2 on 2022-10-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_club_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='all_goals_scored',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_goals_scored',
        ),
        migrations.RemoveField(
            model_name='player',
            name='highest_goal_scorer',
        ),
        migrations.AddField(
            model_name='player',
            name='current_assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='current_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='total_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.CharField(max_length=50),
        ),
    ]
