# Generated by Django 4.0.2 on 2022-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_player_season_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d2standing',
            name='pos',
        ),
        migrations.AddField(
            model_name='club',
            name='division',
            field=models.IntegerField(null=True),
        ),
    ]
