# Generated by Django 4.0.2 on 2022-10-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_d2standing_pos_club_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d1standing',
            name='pos',
        ),
    ]
